### ISSUE TITLE
How to add back in the`api` public function?

### ISSUE THREAD

**Issue by aaronmcadam** [lelylan/simple-oauth2#108]
I've had to upgrade to `1.0.0` to get the `expires_at` bug fix.

I like the changes, but it's broken my code. I was depending upon the `api` method to make authenticated requests to my API. I've tried to poke some holes in the module to expose it again as a public interface, but I'm having some trouble. The following doesn't seem to work:

`index.js`:
```js
    return {
      authorizationCode: authCodeModule(moduleOptions),
      ownerPassword: passwordModule(moduleOptions),
      clientCredentials: clientCredentialsModule(moduleOptions),
      accessToken: accessTokenModule(moduleOptions),
      api: coreModule(moduleOptions).api
    };
```

I know I could just use the `request` module directly myself and pass along the token, but I'd rather not have to copy the code from `call` for header settings like `"Bearer $ACCESS_TOKEN"`. Are there any plans for adding the function back in, or do you suggest clients use `request` themselves?

**Comment by aaronmcadam** [comment]
Is there any way we could incorporate a back port we've created that applies the expiry fix to `0.8.0`? Here it is: https://github.com/crowdlab-uk/simple-oauth2/tree/pc-backport-expiry-fix

**Comment by jonathansamines** [comment]
I am really sorry for you experiencing this. The reason I removed that public API, is because it wasn´t meant for public usage in first place. And people usually reported issues regarding that API because it was not custom enough. The second reason is because I eventually want to replace the inner http library to `wreck` and having that method on the public API would break potentially cause many conflicts to this module users.

Hope the newest version is working well for you.

**Comment by aaronmcadam** [comment]
Hi @jonathansamines, thanks for the response! I really liked the promise API that was provided. I might try `wreck`, thanks!
