### ISSUE TITLE
example of Password Credentials Flow for LinkedIn oauth2 API?

### ISSUE THREAD

**Issue by chovy** [lelylan/simple-oauth2#124]
I'm trying to get the password credentials flow working but I'm not sure what the `credentials` should be when calling `.create(credentials)`

I have an app id and app secret. but not sure what the `credentials.auth` should be.

```
    this.oauth2 = require('simple-oauth2').create({
      client: {
        id: process.env.LINKEDIN_ID,
        secret: process.env.LINKEDIN_SECRET
      },
      auth: {
        tokenHost: 'https://api.linkedin.com',
        authorizePath: 'https://www.linkedin.com/oauth/v2/authorization',
        tokenPath: 'https://www.linkedin.com/oauth/v2/accessToken'
      }
    });
....


    const tokenConfig = {
      username: process.env.LINKEDIN_USER,
      password: process.env.LINKEDIN_PASS
    };

    return this.oauth2.ownerPassword
      .getToken(tokenConfig)
      .then((result) => {
        const token = this.oauth2.accessToken.create(result);

        return token;
      });

```

This doesn't seem to work. I get a "The passed in grant_type is invalid" error.

**Comment by jonathansamines** [comment]
Hey, I have not looked at your code closely, but seems just fine. the "grant type" value is given by the method your are using, in this case is "password" because you are using the owner password grant type. Therefore I would say that is not an issue with your "auth" settings. In any case you can always review what the actual HTTP request is by using the "DEBUG=*simple-oauth2*" variable.

Let me know if that helped you.

**Comment by jonathansamines** [comment]
Please reopen if you are still experiencing this issue.
