### ISSUE TITLE
Anticipate RefreshToken 

### ISSUE THREAD

**Issue by fcioffi** [lelylan/simple-oauth2#138]
Is possibile to anticipate the token expiration so when I call token.expired() it returns true some minutes before expiration?

Thanks,
Francesco

**Comment by jonathansamines** [comment]
I think that is not possible right now, but seems like a use case for #132 even though that approach has its own drawbacks as described in the PR. Is that what you meant?

**Comment by fcioffi** [comment]
Hi jonathansamines.

Yes! It's the use case!

**Comment by jonathansamines** [comment]
@fcioffi as you can see, we are not implement the buffer functionality. However the readme was updated to reflect the use-case it's drawbacks and a possible solution.

Hope that helps!

**Comment by fcioffi** [comment]
Hi @jonathansamines, thanks for your info.

But I don't understand how do you suggest to resolve the issue? Where the README was updated?

I understand that you would like to resolve the issue not at library level but an optional parameter on function token.expired() for a subtraction?

Thanks,
FC

**Comment by jonathansamines** [comment]
Hi @fcioffi the readme was updated at [Access token section](https://github.com/lelylan/simple-oauth2#access-token-object). The reason why we are not willing to resolve this at the library, is because of the drawbacks described at #132, being the main reason the arbitrariety of the time that could be used as buffer expiration value.
