### ISSUE TITLE
Access Token Error Bad Request

### ISSUE THREAD

**Issue by khansohail11523** [lelylan/simple-oauth2#197]
I used this lib, it works good for me and it able to redirects to my tokenHost, after that when I'm authorizing to have token, the code goes into catch block. when I have valid client ID n Secret , and it gives me  "Access Token Error Bad Request". please respond.

**Comment by bluestreek18** [comment]
I had the same issue when OAuth to the mailchimp api using this lib. It required an extra parameter of "redirect_uri" as well as that the body is passed as form data instead of I think JSON that this library sends. I ended up just doing this part of the request myself and using the library for the rest.

`// const result = await oauth2.authorizationCode.getToken(options)

const result = await request({
  uri: 'https://login.mailchimp.com/oauth2/token',
  method: 'POST',
  gzip: true,
  form: {
    code: req.query.code,
    grant_type: 'authorization_code',
    redirect_uri: 'http://localhost:xxxx/xxxx',
    client_id: credentials.client.id,
    client_secret: credentials.client.secret
  }
})`

I'm not sure this library can really "fix" this without some big modifications and I believe the way mailchimp is doing it is against the OAuth2 spec?

**Comment by jonathansamines** [comment]
@khansohail11523 @bluestreek18 You can provide additional arguments when invoking the `getToken` function. See the [docs](https://github.com/lelylan/simple-oauth2#authorization-code-flow) for additional information.

The body format (form or json) can also be configured with `options.bodyFormat`. See the [docs](https://github.com/lelylan/simple-oauth2#options).

If the above suggestions don't work for you, please provide additional information regarding the issue, ideally with a reproduction example.
