### ISSUE TITLE
getAuthorizationHeaderToken causes issue with special character "@"

### ISSUE THREAD

**Issue by BorntraegerMarc** [lelylan/simple-oauth2#226]
When the client secret contains an `@` character then this method: https://github.com/lelylan/simple-oauth2/blob/5aff7c0a768df53a1c7d8d554be22ec7226984ae/lib/encoding.js#L17

I fixed it locally by switching the line to: `const encodedCredentials = `${clientID}:${clientSecret}`;`

Also according to the specs: https://tools.ietf.org/html/rfc6749#section-2.3.1 I'm not sure whether the authentication header should be encoded base64 or just URL save.

But I wanted to raise the question why `encodeURIComponent` and especially why `.replace(/%20/g, '+')` is called?

**Comment by 0x300** [comment]
From that rfc link:

> The client identifier is encoded using the
   "application/x-www-form-urlencoded" encoding algorithm per
   Appendix B, and **the encoded value is used as the username; the client
   password is encoded using the same algorithm** and used as the
   password.

I think that the line mentioned by @BorntraegerMarc shouldn't assume the client id and server id aren't already properly encoded. Passing the correct credentials for the authorization header should be the responsibility of the developer using this module. 

Also, slightly off topic, but the documentation for simple-oauth2 should probably also be updated to mention that passing the Authorization header in the http options object will just be overridden if this feature continues to exist.

**Comment by jonathansamines** [comment]
@BorntraegerMarc The reason for that encoding functionality is because of [Appendix B](https://tools.ietf.org/html/rfc6749#appendix-B) of that rfc. 

@0x300 I would rather say the contrary, most developers are not even aware of the encoding mechanism that the oauth2 spec mandates. Will try to further document that is indeed happening though.

Regarding the second point, you are right. Will also document that. Thanks!
