### ISSUE TITLE
Module parse failed: Unexpected character '#'

### ISSUE THREAD

**Issue by AKK9** [lelylan/simple-oauth2#323]
```
ERROR in ./node_modules/simple-oauth2/lib/client.js 19:2
Module parse failed: Unexpected character '#' (19:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| module.exports = class Client {
>   #config = null;
|   #client = null;
| 
```

Having this issue when attempting to use V4.

My webpack config is:
```
{
  entry: APP_ENTRY_FILEPATH,
  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader',
        options: babelConfig,
      },
    ],
  },
  resolve: { extensions: ['.js', '.jsx', '.ts', '.tsx'] },
  target: 'node',
  output: {
    path: BUILD_OUTPUT_DIR,
    filename: 'handlers.js',
    libraryTarget: 'commonjs2',
  },
}
```

And babel config is:
```
{
  presets: [
    '@babel/typescript',
    [
      '@babel/env',
      {
        targets: { node: '12' },
      },
    ],
  ],
  plugins: ['@babel/proposal-object-rest-spread'],
}
```

Is this an issue with my configuration?

**Comment by jonathansamines** [comment]
@AKK9 Can you confirm your runtime environment is Node 12?

**Comment by AKK9** [comment]
@jonathansamines Yes it is v12.16.1

**Comment by jonathansamines** [comment]
@AKK9 I am unfamiliar with the use of webpack on this context. Perhaps you need an additional [transform](https://babeljs.io/blog/2019/01/21/7.3.0#private-instance-accessors-getters-and-setters-9101-https-githubcom-babel-babel-pull-9101l) to make it work with webpack?

**Comment by rppld** [comment]
Seeing the same issue with v4 in a NextJS app. Next ships their own webpack config under the hood. Modifying that to make this util work isn’t the way to go here imo.

**Comment by jonathansamines** [comment]
@rppld You don't usually to directly modify the webpack configuration. Most of the times, those tools respect the `.babelrc.json` configuration where you can add the missing transforms. Do you have any other alternative in mind? (stop using private class fields is not an option).

**Comment by jonathansamines** [comment]
@rppld We can add transpilation to this module, but there is a couple of things to keep in mind:

- It was always been designed for use in Node.js servers. Most of the authorization flows implemented by this library, can only be safely used when used on a secure server component. Depending on your use on the client-side, it might not be secure. Because of this, we never officially supported client environments. 

- Even if we compile this dependency, we depend on other libraries which also use features and syntax no supported in environments < Node 12. So, you'll always have to compile those dependencies anyway

- A third alternative is to ship a javascript bundle only useful for bundlers such as webpack. This might be our better option, but I have no idea of how to do that. Feel free to submit a PR with such support if you are interested.

**Comment by skeletorkun** [comment]
For a beginner like me, this is such a pain to use from within create-react-app.. It would have been a lot better to have this pre-transpiled.

**Comment by jonathansamines** [comment]
@skeletorkun Sure, a couple things to keep in mind:

- Be pretty cautions when using this library on a `create-react-app` generated application. This library is designed for server applications, not because we don't want to support browsers, but rather because the OAuth 2.0 grant types implemented are not safe to use in a client (browser) application. 

- I am not against adding some pre-compilation step so tools like babel are happy with the module. I am not however, devoting any time for such support for now. I am always open to pull request in case anyone wants to give it a try though.

**Comment by AKK9** [comment]
Due to changes not related to this issue I ended up not using this library (or any Auth related functionality).

My original use case was on a node server so the warnings regarding those Auth flows on the client do not apply.

I was surprised that of the thousands of dependencies in my application, this one needs special treatment. My webpack was excluding

**Comment by lropero** [comment]
So which is the babel plugin that will make this error go away?

**Comment by lropero** [comment]
<img width="432" alt="Captura de Pantalla 2020-06-18 a la(s) 14 34 55" src="https://user-images.githubusercontent.com/4450399/85053803-71fc4380-b171-11ea-8326-84819b34a192.png">

This piece of code taken from `node_modules/simple-oauth2/lib/grants/authorization-code.js` (and among other files) is throwing this error.. what are those `#`? How should I tell Webpack how to deal with them?

**Comment by lropero** [comment]
Ok I decided to use `client-oauth2` instead of `simple-oauth2` since I'm working on a frontend SPA.

**Comment by choeller** [comment]
@jonathansamines why did you close this issues? Is there a solution to the problem? I'm still struggling with the same issue.

**Comment by jonathansamines** [comment]
@choeller Please open a new issue with a complete reproduction of the problem. Please also keep in mind what has  already been discussed in this issue.
