### ISSUE TITLE
SyntaxError: Invalid or unexpected token in client.js:19

### ISSUE THREAD

**Issue by muatik** [lelylan/simple-oauth2#336]
#### Context

* *node version*: v10.20.1
* *module version*:
* *environment* (e.g. node, browser, native): node
* *any other relevant information*:

#### How can we help?

I installed the library following the instructions in README file. But when I import the library and try to run it via node, I get the following error, probably the sharp sign is somehow not allowed in my environment.

```
/.../oauth-example-2/node_modules/simple-oauth2/lib/client.js:19
  #config = null;
  ^

SyntaxError: Invalid or unexpected token
...
```

```js
const { AuthorizationCode } = require('simple-oauth2');

```

**Comment by jonathansamines** [comment]
@muatik See our [minimum requirements](https://github.com/lelylan/simple-oauth2#requirements) for v4. If you need to support Node 10, use v3.

**Comment by aidandavis** [comment]
Hi, I've resolved this error and want to leave this comment for future people hitting this issue. As I've come to this issue from google many times and no obvious solution is given above.

I was deploying firebase functions for node 12 and couldn't understand why I had this problem. Turns out I was deploying from a computer with an older node version (8 or something) and that was causing the Firebase upload scripts to fail.

So it's not just the node version of the cloud functions, it's also the node version of the computer you're deploying from. Worth noting your computer's node version can be 16+ and firebase functions still at 12.
