### ISSUE TITLE
drop site parameter

### ISSUE THREAD

**Issue by andrenarchy** [lelylan/simple-oauth2#55]
The `site` parameter doesn't work for a couple of oauth2 providers (e.g., google and ORCID) because the URLs for initiating the oauth2 dance and obtaining the token have different domains. Example for google:

 * authorization URL: `https://accounts.google.com/o/oauth2/auth`
 * token URL: `https://www.googleapis.com/oauth2/v3/token`

I currently fix this by setting `site = ' '` (mind the whitespace!). However, this is certainly not clean and it would be great if the module could support this directly. A clean solution would be to provide full URLs for everything in the config and to drop the `site` parameter (or to allow it to be empty). What do you think?

**Comment by jonathansamines** [comment]
This problem was already reported in a couple of issues #40, #29.  I don´t like the "site property drop" since it is a breaking change. But what´s about ignoring the site property on every internal change, if not present, so in this way we can issue full path requests on this cases. That option was already discussed on #39.

I think it´s a viable option, but requires some extra work to make it work and test if doesn´t break anything. So do you think that the suggested solution it´s the best or there is another approach? @andreareginato @andrenarchy

**Comment by andrenarchy** [comment]
If you don't want to break the API then there's probably no other way than to allow an undefined site. It also shouldn't be too hard. Maybe I can prepare a PR later today...

**Comment by fcanela** [comment]
I am facing the same issue with Fitbit API.

Maybe a non-breaking solution could be allowing the client to set up a token/authorization URL, being the Path setting used if no url established.

**Comment by jegsar** [comment]
It appears that token url should already work if it is an absolute path all all requests created from it go through the api function in core which checks for, 

isAbsoluteUrl = path.lastIndexOf('http://', 0) === 0 || path.lastIndexOf('https://', 0) === 0;

authorization URL is created elsewhere so I have modified that line to check for the same

Simple enough change so I am submitting a pull request for it.

**Comment by jonathansamines** [comment]
Closed by #75.
