### ISSUE TITLE
Token helper doesn’t play well with session

### ISSUE THREAD

**Issue by sallar** [lelylan/simple-oauth2#59]
Just receiving the access token is not enough by itself, in real-world scenario, you have to save the access token to session. Now, on second page load, if I try to do:
``` javascript
oauth2.accessToken.create(req.session.token);
```
The token never expires because you always add seconds to current time: `(new Date).addSeconds(token.expires_in)` So I had to do something like this:

```javascript
function create(token) {
  // Re-add refresh_token if not present
  if (this.token && 'refresh_token' in this.token) {
    token.refresh_token = this.token.refresh_token;
  }

  // Restore timestamp if already created before
  this.token = token;
  this.token.expires_at = this.token.expires_at ?
      (new Date(this.token.expires_at)) : (new Date).addSeconds(token.expires_in);
  return this;
}
```
And save the resulting object to session instead of the original token. Because session can’t hold javascript functions and classes, On each page load, token helper is recreated from that object.

I might be far off here, but am I missing something?

**Comment by gillesdemey** [comment]
I've had to come up with a similar work-around. The problem is indeed that the `expires_at` property is created again every time you create a new token wrapper.

When saving the tokens to a database and retrieving them again, the token wrapper modifies the existing property.

I'll create a formal PR for this when I find some time.
